image: alpine

variables:
  ISO_NAMESPACE: "alegsan"
  ISO_PROJECT: "ssh-archiso"
  ISO_BRANCH: "master"
  ISO_JOB: "build-archiso"
  ISO_URL: "https://gitlab.com/$ISO_NAMESPACE/$ISO_PROJECT/-/jobs/artifacts/$ISO_BRANCH/download?job=$ISO_JOB"

stages:
  - install

before_script:
  - apk update
  - apk add qemu-system-x86_64 qemu-img openssh

install_andreas:
  stage: install
  tags:
  - docker
  - alegsan
  script:
    - wget "$ISO_URL" -O archiso.zip
    - unzip archiso.zip && rm archiso.zip
    - qemu-img create arch-linux.img 10G
    - qemu-system-x86_64 -enable-kvm -hda arch-linux.img -cdrom archlinux-*.iso -boot d -m 512 -net user,hostfwd=tcp::10022-:22 -net nic -daemonize -display none
    - until ssh -o ConnectTimeout=2 -o StrictHostKeyChecking=no -p 10022 root@localhost "echo \"hello archlinux\""; do sleep 10; echo "Trying again..."; done
    - ssh root@localhost -o StrictHostKeyChecking=no -p 10022 "curl -L https://github.com/schmidtandreas/arch-install/archive/master.tar.gz | tar zxvf -"
    - ssh root@localhost -o StrictHostKeyChecking=no -p 10022 "arch-install-master/arch-install.sh -d -c arch-install-master/configs/andreas_notebook.csv"
