image: alpine

stages:
  - install

before_script:
  - apk update
  - apk add qemu-system-x86_64 qemu-img openssh bash ovmf

install_andreas:
  stage: install
  only:
    - master
    - /^andreas_.*/
  tags:
  - docker
  - andreas
  script:
  - bash -x test/installation.sh "andreas_notebook.csv" "$CI_COMMIT_REF_NAME"
  - bash -x test/installation.sh "andreas_eit.csv" "$CI_COMMIT_REF_NAME"

install_alegsan:
  stage: install
  only:
    - master
    - /^alegsan_.*$/
  tags:
  - docker
  - alegsan
  script: bash -x test/installation.sh "alegsan_tp_x260.csv" "$CI_COMMIT_REF_NAME"
