image: alpine

stages:
  - install

before_script:
  - apk update
  - apk add qemu-system-x86_64 qemu-img openssh bash ovmf

install_andreas:
  stage: install
  tags:
  - docker
  - andreas
  script: bash test/installation.sh andreas_notebook.csv

install_alegsan:
  stage: install
  only:
    - master
  tags:
  - docker
  - alegsan
  script: bash -x test/installation.sh alegsan_tp_x260.csv
